### PR TITLE
add http option for local development

### PR DESCRIPTION
**Pull request by cinqi**

### CODE REVIEW

**Comment by jeremydaly** [comment]
Looks good. I'll merge this and make a few code styling changes.

**Comment by jeremydaly** [comment]
Hey @cinqi,

Thanks for bringing this to my attention and adding the pull request. After I merged it, I did some more research, and the `RDSDataService` has an `sslEnabled` switch that allows you to turn off SSL (set to `true` by default). I like to keep parity with SDK params if possible, so I changed it to this instead. Still works the same way, you just need to set `sslEnabled: false` in order to support your use case.

Thanks again,
Jeremy

**Comment by cinqi** [comment]
Hi!

sslEnabled is better option name. 

However, in addition to setting that to false, the sslAgent should not be set in order to http to work. 

With sslEnabled: false I get error 
`Protocol "http:" not supported. Expected "https:"`

If I comment out following line, everything works:
`AWS.config.update({ httpOptions: { agent: sslAgent } })`

**Comment by jeremydaly** [comment]
Hmm, try setting `keepAlive` to `false`.

**Comment by cinqi** [comment]
**Doh!**  Yes, that works.

**Pull request merged**
